/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class YocoPaymentInitiate { 
    amount?: number
    currency?: string = "ZAR"
    successUrl?: string
    metadata?: YocoPaymentMetadata
    lineItems?: YocoLineItem[]
    processingMode?: string
}

export class YocoPaymentMetadata {
    checkoutId?: string
    externalId?: string
}

export class YocoPaymentInitiateResponse { 
    redirectUrl?: string
    id?: string
    status?: string
}


export interface YocoLineItem {
    displayName: string;
    quantity: number;
    pricingDetails: YocoPricingDetails;
    description?: string | null;
}

export interface YocoPricingDetails {
    price: string;
}

